language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    # Latest dependencies with all PHP versions
    - php: 7.2
    - php: 7.2
      env: COMPOSER_UPDATE_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.3
    - php: 7.3
      env: COMPOSER_UPDATE_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.4
    - php: 7.4
      env: COMPOSER_UPDATE_FLAGS='--prefer-lowest --prefer-stable'

      # Ignore the platform requirements for the upcoming PHP version
    - php: nightly
      env:
          PHP_INI='xdebug.mode=coverage'
    - php: nightly
      env:
          COMPOSER_UPDATE_FLAGS='--prefer-lowest --prefer-stable'
          PHP_INI='xdebug.mode=coverage'
  allow_failures:
    - php: nightly
  fast_finish: true

branches:
  only:
    - master
    - develop
    - 2.x

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction
  - if [[ -n $COMPOSER_UPDATE_FLAGS ]]; then php composer.phar update $COMPOSER_UPDATE_FLAGS; fi
  - if [[ -n $PHP_INI ]]; then echo $PHP_INI >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi

script:
  - mkdir -p build/logs;
  - composer unit-tests
  - composer integration-tests

after_success:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  email:
    - danny.vandersluijs@icloud.com