name: Run tests

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    name: PHP ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - php: 7.2
            allow_fail: false
            name: 'PHP 7.2 with latest deps'
          - php: 7.2
            allow_fail: false
            composer_update_flags: '--prefer-lowest --prefer-stable'
            name: 'PHP 7.2 with lowest stable deps'
          - php: 7.3
            allow_fail: false
            name: 'PHP 7.3 with latest deps'
          - php: 7.3
            allow_fail: false
            composer_update_flags: '--prefer-lowest --prefer-stable'
            name: 'PHP 7.3 with lowest stable deps'
          - php: 7.4
            allow_fail: false
            name: 'PHP 7.4 with latest deps'
          - php: 7.4
            allow_fail: false
            composer_update_flags: '--prefer-lowest --prefer-stable'
            name: 'PHP 7.4 with lowest stable deps'
          - php: 8.0
            allow_fail: true
            php_ini: 'xdebug.coverage_enable=On'
            name: 'PHP 8.0 with latest deps'
          - php: 8.0
            allow_fail: true
            composer_update_flags: '--prefer-lowest --prefer-stable'
            php_ini: 'xdebug.coverage_enable=On'
            name: 'PHP 8.0 with lowest stable deps'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Setup PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: xdebug

    - name: Update php.ini
      if: matrix.php_ini
      run: echo ${{ matrix.php_ini }} >> $ini_file

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install ${{ matrix.composer_flags }}
      continue-on-error: ${{ matrix.allow_fail }}

    - name: Update dependencies
      if: matrix.composer_update_flags
      run: composer update ${{ matrix.composer_update_flags }}
      continue-on-error: ${{ matrix.allow_fail }}
      
    - name: Create log folder
      run: mkdir -p build/logs;

    - name: Run unit tests
      run: composer unit-tests
      continue-on-error: ${{ matrix.allow_fail }}

    - name: Run integration tests
      run: composer integration-tests
      continue-on-error: ${{ matrix.allow_fail }}